### PR TITLE
Merge Composition Compiler code

### PR DESCRIPTION
**Pull request by pa-t**
Merge work from fork

### CODE REVIEW

**Comment by smancill** [comment]
I will be direct. I won't merge this and I will ask you to start over.

You cannot make the mistake of start working on something without even mention it to me before, asking me how to start and where the modifications should be done. The code will go into production, and I am responsible for it, and I will be maintaining it, so it is in my best interest that the merged code is as good as possible. That also counts to the way you present the code as a series of commits, and not just the code as a whole.

I need you to learn and pay attention to the code you deliver. Again, not just the code, also how you make commits. This PR is just the Java code dumped with C++ syntax to  make it compile. And the Git history is a mess.

Each commit must present a single self-contained change. Commits like `working on compiler`, `working again`, `now it works` are useless and just noise, and do not help at all to understand what changed in the code. You have to take time to learn Git, and stop using whatever interface is presented by the IDE that adds everything in the working directory at a random point, commit it with a dummy message and calling it a day. You have to review what you are going to commit, make sure that the changes are related, and stop adding binary/configuration files and then creating  an extra commit just to remove those files, because they are never removed from the history and they will be polluting the object database forever.

These are good links to start figuring out Git:

- http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- https://chris.beams.io/posts/git-commit/
- https://github.com/mockito/mockito/wiki/Using-git-to-prepare-your-PR-to-have-a-clean-history
- http://www.siliconfidential.com/articles/15-seconds-to-cleaner-git-history/
- https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request
- http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html
- http://kevhuang.com/cleaning-up-your-git-commit-history/
- https://mtyurt.net/2017/08/08/git-using-advanced-rebase-features-for-a-clean-repository/

You'll have to learn rebase. Reviews will point changes that need to be addressed, and those changes should be done by rewriting the commits instead of adding `Fix this` commits on top.
Then the PR should be updated with a force pull. If you have questions, then ask me how to do something.

Also, I won't be adding the IDE output files to the `.gitignore` for now. To ignore them, use your local `.git/info/exclude` file.

Regarding the code, you are not following the existing code standard. When you start working on a project, you have to do as the project already does. Consistency is the most important thing on code style. Variable names are no camel case, indentation style is based on K&R, lines are less than 80 characters long, each file should have a specific copyright information, etc.

And you are not following my instructions. The first thing I told you was that the code should compile from the command line. If it works in the IDE is irrelevant. Continuos integration, deployment scripts, Docker builds, etc, all run in servers by using command line tools.

Now, copying the Java code literally is not the proper way to write C++. You just created a bunch of classes with all the code in the headers, instead of separating declaration and definition. And you should not just copy the Java implementation and expect it to work. You should not present hundred of lines of code at once, with a messy history, and not a single test. You have to think that there will be people trying to review and understand the code, and you have to present it in the most clear way possible. I need you to develop the compiler as incremental steps, each one adding a new parsing feature. Everything fully tested.

The composition compiler code should go in `src/composition.hpp` and `src/composition.cpp`. There is a `SimpleCompiler` class in there. You have to add the `CompositionCompiler` class and all helper classes. You have to present a plan. Understand what is a composition, what possible cases and combinations have to be covered. Start from simple compositions, make it work, commit. Then make it work for multiple sentences, commit. Then make it work for conditionals, etc. Push the branch constantly to get feedback, or ask questions on Skype or by mail.

The unit tests go in `test/composition_compiler_test.cpp`. The goal of the composition compiler is to identify the current service in the given composition, and report back to which services the output should go next, and the unit tests should be testing that output for the different ways to write a composition.

Create another PR once you start working in the proper place, following the code standard, and presenting a clean history.

**Comment by pa-t** [comment]
Hi Sebastian,

Thank you for this and I will follow these instructions now. The reason I
did it the previous way was because I was told I would need everything to
be implemented in a week, which would be this upcoming Monday so I've been
rushing to get this implemented and working in the quickest way possible in
the 20 hours that I am able to work on it. I will begin working on it the
way you have described now with regular pull requests and contact with you.

Thanks,
Patrick

**Comment by gurjyan** [comment]
Patrick,
I asked you to present a report at the meeting, and I don't anticipated a ready key implementation. I need you to show your design choices and a status/progress report at the meeting next Tuesday.
The proper way to develop within a group is to create your own branch and merge it with the master after vigorous tests and group mutual agreement to accept changes. 
So, don't be intimidated, we all did something unorthodox at some point and we learned from our mistakes. Please follow material that Sebastian presented, learn and again I will suggest branching and developing in your specific branch.

**Comment by pa-t** [comment]
Vardan,

That is completely my misunderstanding then, I was under the assumption
that you were wanting an implementation ready. I will have a report ready
in that case.

Thanks,
Patrick

**Pull request closed without merging**
